# Generated by Django 5.2.7 on 2025-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer1',
        ),
    ]
