# Generated by Django 5.2.7 on 2025-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApp', '0002_studentcourse_delete_customer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
