# Generated by Django 5.2.7 on 2025-10-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApp', '0003_alter_studentcourse_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
